version: 0.1

phases:
  install:
    commands:
      - pip install --upgrade -t './code/lib' -r requirements.txt
  build:
    commands:
      - for template in $(ls ./templates); do echo "Packaging templates/${template}..."; aws cloudformation package --template-file templates/${template} --s3-bucket $S3_BUCKET --output-template-file packaged-${template}; done
  post_build:
    commands:
      - for template in $(ls ./templates); do echo "Deploying templates/${template}..."; aws cloudformation deploy --template-file packaged-${template}  --stack-name "FinancialFunction-${template%.yaml}" --capabilities CAPABILITY_IAM --region us-east-1; done
