version: 0.1

phases:
  install:
    commands:
      - pip install --upgrade -t './code/lib' -r requirements.txt
  build:
    commands:
      - aws cloudformation package --template-file templates/${FINANCIAL_ABBREVIATION}.yaml --s3-bucket $S3_BUCKET --output-template-file packaged-${FINANCIAL_ABBREVIATION}.yaml
  post_build:
    commands:
      - aws cloudformation deploy --template-file packaged-${FINANCIAL_ABBREVIATION}.yaml  --stack-name "${FINANCIAL_ABBREVIATION}FinancialFunction" --capabilities CAPABILITY_IAM --region us-east-1
artifacts:
  type: zip
  files:
    - packaged-${FINANCIAL_ABBREVIATION}.yaml