AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Resources:
  # Modified Internal Rate of Return financial function
  MIRR:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: 'lambda_handlers.mirr_handler'
      CodeUri: '../code'
      Runtime: 'python2.7'
      Timeout: 30
      MemorySize: 256
